# Generated by Django 3.1.7 on 2021-02-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=3)),
                ('unit_descriptor', models.CharField(max_length=15)),
                ('unit_code', models.PositiveIntegerField()),
                ('restrict_code', models.CharField(max_length=5)),
                ('rating', models.PositiveIntegerField()),
                ('bl_link', models.URLField()),
                ('coc_link', models.URLField()),
            ],
        ),
    ]
