# Generated by Django 3.1.7 on 2021-03-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0002_auto_20210303_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='unit_descriptor',
            field=models.CharField(max_length=15),
        ),
    ]
