# Generated by Django 3.1.7 on 2021-03-08 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0003_auto_20210308_0958'),
        ('containers', '0003_auto_20210308_1011'),
    ]

    operations = [
    ]
