# Generated by Django 3.1.7 on 2021-02-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=10)),
                ('company_code', models.CharField(max_length=3)),
                ('product', models.CharField(max_length=25)),
                ('operator', models.CharField(max_length=50)),
                ('total_weight', models.PositiveIntegerField()),
                ('contract_date', models.DateField()),
                ('restrictions', models.CharField(max_length=20)),
                ('curr_containers', models.JSONField()),
            ],
        ),
    ]
