# Generated by Django 3.1.7 on 2021-03-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='pend_containers',
            field=models.JSONField(null=True),
        ),
    ]
