# Generated by Django 3.1.7 on 2021-03-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_pend_containers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='pend_containers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
