# Generated by Django 3.1.7 on 2021-03-08 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_auto_20210308_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_date_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
