# Generated by Django 3.1.7 on 2021-03-08 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20210308_1011'),
        ('contracts', '0006_auto_20210308_1107'),
    ]

    operations = [
    ]
